[tool.poetry]
name = "AnalysisGUI"
version = "0.1.0"
description = "AC/DC cell analysis"
authors = ["Victor Ionescu <vionescu@biodyn.ro>"]
license = "MIT"
readme = "README.md"
packages = [{include = "AnalysisGUI", from = "src"}]

[tool.poetry.build]
script = "build.py"
generate-setup-file = false

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "~1.26"
pyqtgraph = "^0.13.7"
pyqt5 = "^5.15.11"
opencv-python = "^4.11.0.86"
matplotlib = "^3.10.1"
cython = "^3.0.12"
natsort = "^8.4.0"
aicsimageio = "^4.14.0"
omnipose = "^1.0.6"
scipy = "~1.11"
loky = "^3.5.1"
dill = "^0.3.9"

[tool.poetry.scripts]
startGUI = 'AnalysisGUI.__main__:runApp'
[build-system]
requires = ["poetry-core","Cython","setuptools","numpy"]
build-backend = "poetry.core.masonry.api"
